import {
  Award,
  BarChart3,
  Building2,
  Clock,
  Cloud,
  Code2,
  Database,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Layers,
  Layout,
  Lock,
  MessageCircle,
  Monitor,
  Rocket,
  Settings2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Users,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconComponents: Record<string, LucideIcon> = {
  layout: Layout,
  "building-2": Building2,
  "settings-2": Settings2,
  zap: Zap,
  "message-circle": MessageCircle,
  layers: Layers,
  "shield-check": ShieldCheck,
  headphones: Headphones,
  target: Target,
  rocket: Rocket,
  star: Star,
  "code-2": Code2,
  smartphone: Smartphone,
  monitor: Monitor,
  cloud: Cloud,
  database: Database,
  "trending-up": TrendingUp,
  users: Users,
  lock: Lock,
  heart: Heart,
  globe: Globe,
  clock: Clock,
  award: Award,
  sparkles: Sparkles,
  "bar-chart-3": BarChart3,
  "help-circle": HelpCircle,
};

export function getIconComponent(name: string): LucideIcon {
  return iconComponents[name] ?? Star;
}
